### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#35]
```
июн 19 22:06:22 pc systemd[1]: nohang.service: Service RestartSec=100ms expired, scheduling restart.
июн 19 22:06:22 pc systemd[1]: nohang.service: Scheduled restart job, restart counter is at 582.
июн 19 22:06:22 pc systemd[1]: Stopped Highly configurable OOM prevention daemon.
июн 19 22:06:22 pc systemd[1]: Started Highly configurable OOM prevention daemon.
июн 19 22:06:22 pc nohang[3204]: Config: /etc/nohang/nohang.conf
июн 19 22:06:22 pc nohang[3204]: Monitoring has started!
июн 19 22:06:22 pc nohang[3204]: Traceback (most recent call last):
июн 19 22:06:22 pc nohang[3204]:   File "/usr/sbin/nohang", line 3075, in <module>
июн 19 22:06:22 pc nohang[3204]:     swap_free, swap_total) = check_mem_swap_ex()
июн 19 22:06:22 pc nohang[3204]:   File "/usr/sbin/nohang", line 1298, in check_mem_swap_ex
июн 19 22:06:22 pc nohang[3204]:     if swap_total > swap_min_sigkill_kb:
июн 19 22:06:22 pc nohang[3204]: UnboundLocalError: local variable 'swap_min_sigkill_kb' referenced before assignment
июн 19 22:06:22 pc systemd[1]: nohang.service: Main process exited, code=exited, status=1/FAILURE
июн 19 22:06:22 pc systemd[1]: nohang.service: Failed with result 'exit-code'.
```

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/78c1e61a361e083c5ab89a8ac81f56625911e7d6

**Comment by hakavlad** [comment]
```
июл 02 22:34:38 pc nohang[29639]: Memory status that requires corrective actions (soft threshold exceeded):
июл 02 22:34:38 pc nohang[29639]:   MemAvailable [869 MiB, 8.9 %] <= mem_min_sigterm [981 MiB, 10.0 %]
июл 02 22:34:38 pc nohang[29639]:   SwapFree [0 MiB, 0.0 %] <= swap_min_sigterm [0 MiB, - %]
июл 02 22:34:38 pc nohang[29639]: Try to implement a corrective action...
июл 02 22:34:38 pc nohang[29639]: Regexp '' matches with name 'tail'
июл 02 22:34:38 pc nohang[29639]: Execute the command: kill -SEGV 29655
июл 02 22:34:38 pc nohang[29639]: Exit status: 0; exe duration: 0.001 sec
июл 02 22:34:38 pc nohang[29639]: Traceback (most recent call last):
июл 02 22:34:38 pc nohang[29639]:   File "/usr/sbin/nohang", line 1680, in implement_corrective_action
июл 02 22:34:38 pc nohang[29639]:     log(preventing_oom_message)
июл 02 22:34:38 pc nohang[29639]: UnboundLocalError: local variable 'preventing_oom_message' referenced before assignment
июл 02 22:34:38 pc nohang[29639]: During handling of the above exception, another exception occurred:
июл 02 22:34:38 pc nohang[29639]: Traceback (most recent call last):
июл 02 22:34:38 pc nohang[29639]:   File "/usr/sbin/nohang", line 3143, in <module>
июл 02 22:34:38 pc nohang[29639]:     x0, psi_threshold, zram_threshold, zram_info, psi_info)
июл 02 22:34:38 pc nohang[29639]:   File "/usr/sbin/nohang", line 1683, in implement_corrective_action
июл 02 22:34:38 pc nohang[29639]:     preventing_oom_message = key
июл 02 22:34:38 pc nohang[29639]: UnboundLocalError: local variable 'key' referenced before assignment
июл 02 22:34:38 pc systemd[1]: nohang.service: Main process exited, code=exited, status=1/FAILURE
июл 02 22:34:38 pc systemd[1]: nohang.service: Failed with result 'exit-code'.
```

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/1ae54155be7544e8e58db31dabcc3cdc80fca989
