### ISSUE TITLE
Bug with GUI notifications

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#86]
```
Feb 12 13:48:26 laptop nohang-desktop[32532]: Exception in thread Thread-4:
Feb 12 13:48:26 laptop nohang-desktop[32532]: Traceback (most recent call last):
Feb 12 13:48:26 laptop nohang-desktop[32532]:   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Feb 12 13:48:26 laptop nohang-desktop[32532]:     self.run()
Feb 12 13:48:26 laptop nohang-desktop[32532]:   File "/usr/lib/python3.6/threading.py", line 864, in run
Feb 12 13:48:26 laptop nohang-desktop[32532]:     self._target(*self._args, **self._kwargs)
Feb 12 13:48:26 laptop nohang-desktop[32532]:   File "/usr/local/bin/nohang", line 286, in send_notification
Feb 12 13:48:26 laptop nohang-desktop[32532]:     list_with_envs = root_notify_env()
Feb 12 13:48:26 laptop nohang-desktop[32532]:   File "/usr/local/bin/nohang", line 217, in root_notify_env
Feb 12 13:48:26 laptop nohang-desktop[32532]:     one_env = re_pid_environ(pid)
Feb 12 13:48:26 laptop nohang-desktop[32532]:   File "/usr/local/bin/nohang", line 170, in re_pid_environ
Feb 12 13:48:26 laptop nohang-desktop[32532]:     env = f.read()
Feb 12 13:48:26 laptop nohang-desktop[32532]:   File "/usr/lib/python3.6/codecs.py", line 321, in decode
Feb 12 13:48:26 laptop nohang-desktop[32532]:     (result, consumed) = self._buffer_decode(data, self.errors, final)
Feb 12 13:48:26 laptop nohang-desktop[32532]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 0: invalid start byte
```

See also https://github.com/hakavlad/nohang/issues/85#issuecomment-586655924

**Comment by luni3359** [comment]
Oh yeah, I forgot to mention that I don't see notifications either. I assumed that they didn't show up because the system froze a lot... sorry.

**Comment by hakavlad** [comment]
Should be fixed via https://github.com/hakavlad/nohang/commit/122233ac2f915deee19d0e58013a1f881cf900c9.

@luni3359 Please install the latest version and check GUI notifications.
