### ISSUE TITLE
PermissionError with hidepid=1

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#88]
```
user@PC:~$ nohang
Traceback (most recent call last):
  File "/usr/local/bin/nohang", line 2745, in <module>
    pid_list = alive_pid_list()
  File "/usr/local/bin/nohang", line 1549, in alive_pid_list
    if is_alive(pid):
  File "/usr/local/bin/nohang", line 1528, in is_alive
    with open('/proc/{}/statm'.format(pid), 'rb', buffering=0) as f:
PermissionError: [Errno 1] Operation not permitted: '/proc/1/statm'
user@PC:~$ nohang -v
Traceback (most recent call last):
  File "/usr/local/bin/nohang", line 2745, in <module>
    pid_list = alive_pid_list()
  File "/usr/local/bin/nohang", line 1549, in alive_pid_list
    if is_alive(pid):
  File "/usr/local/bin/nohang", line 1528, in is_alive
    with open('/proc/{}/statm'.format(pid), 'rb', buffering=0) as f:
PermissionError: [Errno 1] Operation not permitted: '/proc/1/statm'
user@PC:~$ nohang -h
Traceback (most recent call last):
  File "/usr/local/bin/nohang", line 2745, in <module>
    pid_list = alive_pid_list()
  File "/usr/local/bin/nohang", line 1549, in alive_pid_list
    if is_alive(pid):
  File "/usr/local/bin/nohang", line 1528, in is_alive
    with open('/proc/{}/statm'.format(pid), 'rb', buffering=0) as f:
PermissionError: [Errno 1] Operation not permitted: '/proc/1/statm'
```

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/a7c329971f4dd3e2a90431268be616123361f085

**Comment by hakavlad** [comment]
$ oom-sort
Traceback (most recent call last):
  File "/usr/local/bin/oom-sort", line 165, in <module>
    oom_score = pid_to_oom_score(pid)
  File "/usr/local/bin/oom-sort", line 18, in pid_to_oom_score
    with open('/proc/' + pid + '/oom_score') as f:
PermissionError: [Errno 1] Operation not permitted: '/proc/2/oom_score'

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/c70b8242d071d177a020177623386630b99d64fb
