### ISSUE TITLE
[PSI] The process fails if the service stops

### ISSUE THREAD

**Issue by hakavlad** [hakavlad/nohang#91]
```
май 03 15:46:06 PC nohang[1972]: PSI:    0.0 | MemAvail: 8917 M, 91.1 % | SwapFree: 9469 M,  96.7 % | dMem:     0 M/s
май 03 15:46:10 PC nohang[1972]: PSI:    0.0 | MemAvail: 8917 M, 91.1 % | SwapFree: 9469 M,  96.7 % | dMem:     0 M/s
май 03 15:46:13 PC nohang[1972]: PSI:    0.0 | MemAvail: 8909 M, 91.0 % | SwapFree: 9469 M,  96.7 % | dMem:    -3 M/s
май 03 15:46:16 PC nohang[1972]: Traceback (most recent call last):
май 03 15:46:16 PC nohang[1972]:   File "/usr/bin/nohang", line 3834, in <module>
май 03 15:46:16 PC nohang[1972]:     psi_avg_value = find_psi_metrics_value(psi_path, psi_metrics)
май 03 15:46:16 PC nohang[1972]:   File "/usr/bin/nohang", line 1312, in find_psi_metrics_value
май 03 15:46:16 PC nohang[1972]:     return float(rline1(psi_path).split(' ')[1].split('=')[1])
май 03 15:46:16 PC nohang[1972]:   File "/usr/bin/nohang", line 1508, in rline1
май 03 15:46:16 PC nohang[1972]:     with open(path) as f:
май 03 15:46:16 PC nohang[1972]: FileNotFoundError: [Errno 2] No such file or directory: '/sys/fs/cgroup/system.slice/fail2ban.service/memory.pressure'
май 03 15:46:16 PC systemd[1]: nohang.service: Main process exited, code=exited, status=1/FAILURE
май 03 15:46:16 PC systemd[1]: nohang.service: Unit entered failed state.
май 03 15:46:16 PC systemd[1]: nohang.service: Failed with result 'exit-code'.
май 03 15:46:16 PC systemd[1]: nohang.service: Service has no hold-off time, scheduling restart.
```

**Comment by hakavlad** [comment]
It may happen with non-system-wide psi_path like 

```
psi_path = /sys/fs/cgroup/system.slice/fail2ban.service/memory.pressure
```

If the service stops, the PSI file of which we are monitoring, then nohang fails.

**Comment by hakavlad** [comment]
https://github.com/hakavlad/nohang/commit/01f17c46904bb13ab7007c10eea13e1264d8f715
