### ISSUE TITLE
MemoryError CDLL

### ISSUE THREAD

**Issue by dim-geo** [hakavlad/nohang#94]
```
11:46:48 gentoo nohang-desktop[2455]: Traceback (most recent call last):
11:46:48 gentoo nohang-desktop[2455]:   File "/usr/local/sbin/nohang", line 5, in <module>
11:46:48 gentoo nohang-desktop[2455]:     from ctypes import CDLL
11:46:48 gentoo nohang-desktop[2455]:   File "/usr/lib/python3.7/ctypes/__init__.py", line 551, in <module>
11:46:48 gentoo nohang-desktop[2455]:     _reset_cache()
11:46:48 gentoo nohang-desktop[2455]:   File "/usr/lib/python3.7/ctypes/__init__.py", line 273, in _reset_cache
11:46:48 gentoo nohang-desktop[2455]:     CFUNCTYPE(c_int)(lambda: None)
11:46:48 gentoo nohang-desktop[2455]: MemoryError
```

nohang desktop fails when started, with the above message.

When the CapabilityBoundingSet is commented out, it works.

https://github.com/hakavlad/nohang/blob/52067444eda2cfbb0ef1748628d1af3ba4a9ae7e/nohang/nohang-desktop.service.in#L39

**Comment by hakavlad** [comment]
Wow, thanks. I have no idea how to fix it.

Other way to fix may be to set `vm.overcommit_memory=1`.

**Comment by dim-geo** [comment]
I tried the suggested workaround but to no avail.

**Comment by hakavlad** [comment]
Maybe it may be fixed by adding yet another capabilities in CapabilityBoundingSet.

You can try to find experimentally what is missing.

List: http://man7.org/linux/man-pages/man7/capabilities.7.html

I originally compiled a list by gradually removing capabilities from full capabilities list like

```
CapabilityBoundingSet=CAP_AUDIT_CONTROL CAP_AUDIT_READ CAP_AUDIT_WRITE CAP_BLOCK_SUSPEND CAP_CHOWN CAP_DAC_OVERRIDE CAP_DAC_READ_SEARCH CAP_FOWNER CAP_FSETID CAP_IPC_LOCK CAP_IPC_OWNER CAP_KILL CAP_LEASE CAP_LINUX_IMMUTABLE CAP_MAC_ADMIN CAP_MAC_OVERRIDE CAP_MKNOD CAP_NET_ADMIN CAP_NET_BIND_SERVICE CAP_NET_BROADCAST CAP_NET_RAW CAP_SETGID CAP_SETFCAP CAP_SETPCAP CAP_SETUID CAP_SYS_ADMIN CAP_SYS_BOOT CAP_SYS_CHROOT CAP_SYS_MODULE CAP_SYS_NICE CAP_SYS_PACCT CAP_SYS_PTRACE CAP_SYS_RAWIO CAP_SYS_RESOURCE CAP_SYS_TIME CAP_SYS_TTY_CONFIG CAP_SYSLOG CAP_WAKE_ALARM
```
You could try it instead of
```
 CapabilityBoundingSet=CAP_KILL CAP_IPC_LOCK CAP_SYS_PTRACE CAP_DAC_READ_SEARCH CAP_AUDIT_WRITE CAP_SETUID CAP_SETGID CAP_SYS_RESOURCE 
```
and exclude CAPs step by step.

**Comment by dim-geo** [comment]
Thanks for the idea!
in my system/python I also need:
CAP_DAC_OVERRIDE

(I didn't try to remove existing ones though)

**Comment by hakavlad** [comment]
```
CapabilityBoundingSet=CAP_KILL CAP_IPC_LOCK CAP_SYS_PTRACE CAP_DAC_READ_SEARCH CAP_DAC_OVERRIDE CAP_AUDIT_WRITE CAP_SETUID CAP_SETGID CAP_SYS_RESOURCE
```
This completely solves the problem, right?

**Comment by dim-geo** [comment]
Yes
